### ISSUE TITLE
Pigeons get replaced with another object when using the mod with pre existing save game.

### ISSUE THREAD

**Issue by ilyaa07** [catsmackaroo/LibertyTweaks#12]
![Снимок экрана 2024-05-15 015955](https://github.com/catsmackaroo/LibertyTweaks/assets/90723091/6bc07f33-8f14-484c-930c-9e209ed1ec0c)
Without the mod

![Снимок экрана 2024-05-15 020210](https://github.com/catsmackaroo/LibertyTweaks/assets/90723091/c0778d9c-3dbb-4253-be4b-fc77c50c452a)
With the mod

**Comment by catsmackaroo** [comment]
Unfortunately, due to the Armored Cops Vests feature, there is no way around it. It is because the files provided for said feature are added yet replace a pre-existing file from the game itself. I don't know of a fix for this yet. If you wish to still use your save from before installing LibertyTweaks, just disable the Armored Cops Have Vests option in LibertyTweaks.ini
