### ISSUE TITLE
Tracker service on map has no text (IV SDK .NET 1.4, Clonks Coding Library 1.6).

### ISSUE THREAD

**Issue by Haxogone** [catsmackaroo/LibertyTweaks#22]

**Comment by Haxogone** [comment]
<img width="1280" alt="Grand Theft Auto 4 Screenshot 2024 07 20 - 23 59 48 42" src="https://github.com/user-attachments/assets/988f9d87-9d8e-4734-bc20-48e14d5a4582">

**Comment by catsmackaroo** [comment]
This bug has been fixed. It was apparently fixed ages ago. I only just now realized the blips are saved into the save itself. I don't think I can help fix your specific save unfortunately, but I may add something into the script to prevent this from happening to someone else, if it's possible.

I found all this out because I disabled Personal Vehicles and the nameless blips were still there. I downloaded another save off GTASnP and it was fine
